package AmavisPM::Model::AmavisDB;

use strict;
use base 'Catalyst::Model::DBIC::Schema';

__PACKAGE__->config(
    schema_class => 'AmavisDB::Schema',
    
    connect_info => {
        dsn => 'dbi:Pg:dbname=amavis',
        user => 'postfix',
        password => 'k0k0puff$',
    }
);

=head1 NAME

AmavisPM::Model::AmavisDB - Catalyst DBIC Schema Model

=head1 SYNOPSIS

See L<AmavisPM>

=head1 DESCRIPTION

L<Catalyst::Model::DBIC::Schema> Model using schema L<AmavisDB::Schema>

=head1 GENERATED BY

Catalyst::Helper::Model::DBIC::Schema - 0.59

=head1 AUTHOR

Mail Domain Admin

=head1 LICENSE

This library is free software, you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut

1;
